route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: telegram
receivers:
- name: telegram
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: *****
    chat_id: *****
    message: '{{ template "telegram.template.message" . }}'
    parse_mode: HTML
templates:
  - /etc/prometheus/*.tmpl
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'dev', 'instance']
